# Jekyll configuration for webtrees.net

title: webtrees
email: greg@subaqua.co.uk
description: >
  webtrees is a web application that allows you to publish your genealogy online,
  collaborate with family members and take control of your data.
latest_version: "2.1.0-alpha.1"
latest_version_20: "2.0.18"
latest_version_17: "1.7.19"
latest_version_14: "1.4.6"
url: "https://webtrees.net"
demo_dev_url: "https://dev.webtrees.net/demo-dev"
demo_stable_url: "https://dev.webtrees.net/demo-stable"
this_github_repo: webtrees/webtrees.github.io
edit_text: Edit this page
baseurl: ""
date_format: "%-d %B %Y"
show_excerpts: true
permalink: pretty
collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title:output_ext
  admin:
    output: true
  develop:
    output: true
  install:
    output: true
  upgrade:
    output: true
  user:
    output: true
paginate: 100
paginate_path: "/blog/page:num/"

# External accounts
main_github_repo:  fisharebest/webtrees

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
